-- find policies coded to a particular treaty profile

select s.SUB_RECORD_NUMBER, s.SUB_CURRENT_EFFECTIVE_DATE, s.SUB_CURRENT_EXPIRATION_DATE
from SUBMISSION s
join QUOTE_BINDER qb on qb.SUB_RECORD_NUMBER = s.SUB_RECORD_NUMBER and qb.QB_SEQUENCE_no = s.QB_SEQUENCE_NO
join RI_HEADER_LEVEL rih on s.SUB_RECORD_NUMBER = rih.SUB_RECORD_NUMBER 
join RI_LAYER_LEVEL rill on rill.HEADER_LEVEL_SKEY = rih.HEADER_LEVEL_SKEY
join RI_MARKET_LEVEL riml on riml.LAYER_LEVEL_SKEY = rill.LAYER_LEVEL_SKEY
join TREATY_PROFILE tp on riml.PROFILE_SKEY = tp.PROFILE_SKEY
where 1=1
--and ( s.SUB_CURRENT_EFFECTIVE_DATE < tp.PROFILE_EFFECTIVE_DATE  OR s.SUB_CURRENT_EFFECTIVE_DATE > tp.PROFILE_EXPIRATION_DATE )
and tp.profile_skey in (253,254)
and s.STATUS_CODE = 'B'

select distinct s.SUB_RECORD_NUMBER, s.SUB_CURRENT_EFFECTIVE_DATE, s.SUB_CURRENT_EXPIRATION_DATE
from SUBMISSION s
join QUOTE_BINDER qb on qb.SUB_RECORD_NUMBER = s.SUB_RECORD_NUMBER and qb.QB_SEQUENCE_no = s.QB_SEQUENCE_NO
join RI_HEADER_LEVEL rih on s.SUB_RECORD_NUMBER = rih.SUB_RECORD_NUMBER 
join RI_LAYER_LEVEL rill on rill.HEADER_LEVEL_SKEY = rih.HEADER_LEVEL_SKEY
join RI_MARKET_LEVEL riml on riml.LAYER_LEVEL_SKEY = rill.LAYER_LEVEL_SKEY
join TREATY_PROFILE tp on riml.PROFILE_SKEY = tp.PROFILE_SKEY
where 1=1
and ( s.SUB_CURRENT_EFFECTIVE_DATE < tp.PROFILE_EFFECTIVE_DATE  OR s.SUB_CURRENT_EFFECTIVE_DATE > tp.PROFILE_EXPIRATION_DATE )
and tp.profile_skey in (241,242)
and s.STATUS_CODE = 'B'



select * from treaty_profile where DEPARTMENT_NUMBER = 100