select qbdo_policy_form from QUOTE_BINDER_D_O where SUB_RECORD_NUMBER = 1094510

select * from submission where programkey = 201

select distinct qbdo_policy_form from QUOTE_BINDER_D_O 
where SUB_RECORD_NUMBER IN 
( select sub_record_number from submission where programkey = 201 )

select s.sub_policy_number, s.sub_record_number, qbdo.qbdo_policy_form, s.CreateDate
from QUOTE_BINDER_D_O qbdo 
join Submission s on s.SUB_RECORD_NUMBER = qbdo.SUB_RECORD_NUMBER
where s.programkey = 201
order by CreateDate

select * from FORM_TYPE where FORM_RECORD_NUMBER IN (206,211,217)

where SUB_RECORD_NUMBER = 1094510


SELECT * FROM [dbo].[Program]
GO


 

select distinct DOCUMENT_SUBTYPE
from DOCUMENTS 
where DEPARTMENT_NUMBER = 100

SELECT * FROM [dbo].[DocumentType]
GO

select * from REFERENCE_TYPE where TYPE_SKEY IN (31,32,173)

select s.DEPARTMENT_NUMBER, s.SUB_POLICY_NUMBER, s.SUB_RECORD_NUMBER, qb.QB_TYPE
 from QUOTE_BINDER qb
join SUBMISSION s on s.SUB_RECORD_NUMBER = qb.SUB_RECORD_NUMBER
where QB_TYPE is not null
and s.CreateDate > '02/01/2007'

select s.DEPARTMENT_NUMBER, s.SUB_POLICY_NUMBER, s.SUB_RECORD_NUMBER, qb.QB_TYPE
 from QUOTE_BINDER qb
join SUBMISSION s on s.SUB_RECORD_NUMBER = qb.SUB_RECORD_NUMBER
where QB_TYPE is not null
and s.CreateDate > '02/01/2007'

select distinct DOCUMENT_TYPE, rt.DESCRIPTION
from DOCUMENTS d
join REFERENCE_TYPE rt on rt.TYPE_SKEY = d.DOCUMENT_TYPE
where DEPARTMENT_NUMBER = 300


select distinct DOCUMENT_TYPE, rt.DESCRIPTION
from DOCUMENTS d
join REFERENCE_TYPE rt on rt.TYPE_SKEY = d.DOCUMENT_TYPE
where DEPARTMENT_NUMBER = 1900

select distinct DOCUMENT_TYPE, rt.DESCRIPTION
from DOCUMENTS d
join REFERENCE_TYPE rt on rt.TYPE_SKEY = d.DOCUMENT_TYPE
where DEPARTMENT_NUMBER = 300
and DOCUMENT_TYPE = 29

select distinct d.DOCUMENT_TYPE, rt.DESCRIPTION
from QB_DOCUMENTS qbd
join DOCUMENTS d on d.DOCUMENT_NUMBER = qbd.DOCUMENT_NUMBER
join REFERENCE_TYPE rt on rt.TYPE_SKEY = d.DOCUMENT_TYPE
join QUOTE_BINDER qb on (qb.SUB_RECORD_NUMBER = qbd.SUB_RECORD_NUMBER and qb.QB_SEQUENCE_NO = qbd.QB_SEQUENCE_NO)
join SUBMISSION s on s.SUB_RECORD_NUMBER = qb.SUB_RECORD_NUMBER
where s.DEPARTMENT_NUMBER IN (1900,300)

select distinct s.DEPARTMENT_NUMBER, qbd.QB_COMPANY_TYPE
from QB_DOCUMENTS qbd
join DOCUMENTS d on d.DOCUMENT_NUMBER = qbd.DOCUMENT_NUMBER
join REFERENCE_TYPE rt on rt.TYPE_SKEY = d.DOCUMENT_TYPE
join QUOTE_BINDER qb on (qb.SUB_RECORD_NUMBER = qbd.SUB_RECORD_NUMBER and qb.QB_SEQUENCE_NO = qbd.QB_SEQUENCE_NO)
join SUBMISSION s on s.SUB_RECORD_NUMBER = qb.SUB_RECORD_NUMBER
where s.DEPARTMENT_NUMBER IN (100,200,1800)

select s.SUB_RECORD_NUMBER, s.SUB_POLICY_NUMBER, d.DOCUMENT_NAME, d.DEPARTMENT_NUMBER, 
       d.DOCUMENT_FILE_NAME, s.CreateDate
from QB_DOCUMENTS qbd
join DOCUMENTS d on d.DOCUMENT_NUMBER = qbd.DOCUMENT_NUMBER
join REFERENCE_TYPE rt on rt.TYPE_SKEY = d.DOCUMENT_TYPE
join QUOTE_BINDER qb on (qb.SUB_RECORD_NUMBER = qbd.SUB_RECORD_NUMBER and qb.QB_SEQUENCE_NO = qbd.QB_SEQUENCE_NO)
join SUBMISSION s on s.SUB_RECORD_NUMBER = qb.SUB_RECORD_NUMBER
where s.DEPARTMENT_NUMBER = 300
and d.DOCUMENT_TYPE = 29
order by s.CreateDate DESC

select qb
ALTER TABLE [dbo].[QB_DOCUMENTS]
    ADD CONSTRAINT [FK__QB_DOCUME__QB_CO__3044E72D]
	FOREIGN KEY([QB_COMPANY_TYPE])
	REFERENCES [dbo].[REFERENCE_TYPE]([TYPE_SKEY])
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION 
GO

from Quote_binder qb


select * 
from REFERENCE_TYPE rt
where rt.CATEGORY_SKEY = 9

select * from REFERENCE_CATEGORY

--and s.CreateDate > '1/1/2005'





select * from RuleBasedDocType



SELECT distinct D.DOCUMENT_NUMBER,D.ORG_NUMBER, D.DOCUMENT_NAME, D.DOCUMENT_PATH, D.DOCUMENT_FILE_NAME, D.DOCUMENT_TYPE,
 D.STATE_ABBREVIATION as DOC_STATE, ACDSX.STATE_ABBREVIATION as APPROVED_STATE, 
acdsx.effective_date, acdsx.expiration_date, d.inactive_date, 
DRC.FIELD+DRC.OPERATOR+DRC.CRITERIAVALUE, D.DEPARTMENT_NUMBER AS DOC_DEPT, 
DR.DEPARTMENT_NUMBER as DOCRULE_DEPT, DR.RULE_SCRIPT, ACDSX.COMMENTS
FROM DOCUMENTS D 
left join DocumentRuleXref DRX 
    on D.DOCUMENT_NUMBER = DRX.DOCUMENT_NUMBER
LEFT JOIN DOCUMENTRULE DR 
		ON DRX.DOCUMENTRULEKEY = DR.DOCUMENTRULEKEY 
LEFT JOIN DOCUMENTRULECRITERIA DRC 
		ON DR.DOCUMENTRULEKEY = DRC.DOCUMENTRULEKEY 
LEFT JOIN RuleBasedDocType rbdt ON D.DOCUMENT_TYPE = rbdt.DocTypeId
LEFT JOIN ApprovedCoDocsStateXref ACDSX ON ACDSX.DOCUMENT_NUMBER = D.DOCUMENT_NUMBER
WHERE 1=1
and (D.DEPARTMENT_NUMBER = 300 or dr.department_number = 300)
and d.org_number = 2
AND D.DOCUMENT_TYPE IS NOT NULL
AND D.DOCUMENT_TYPE NOT IN (35,124,125,163)
--and acdsx.state_abbreviation is null
ORDER BY 1


SELECT distinct D.DOCUMENT_NUMBER,D.ORG_NUMBER, D.DOCUMENT_NAME, D.DOCUMENT_PATH, D.DOCUMENT_FILE_NAME, D.DOCUMENT_TYPE
FROM DOCUMENTS D 
left join DocumentRuleXref DRX 
    on D.DOCUMENT_NUMBER = DRX.DOCUMENT_NUMBER
LEFT JOIN DOCUMENTRULE DR 
		ON DRX.DOCUMENTRULEKEY = DR.DOCUMENTRULEKEY 
LEFT JOIN DOCUMENTRULECRITERIA DRC 
		ON DR.DOCUMENTRULEKEY = DRC.DOCUMENTRULEKEY 
LEFT JOIN RuleBasedDocType rbdt ON D.DOCUMENT_TYPE = rbdt.DocTypeId
LEFT JOIN ApprovedCoDocsStateXref ACDSX ON ACDSX.DOCUMENT_NUMBER = D.DOCUMENT_NUMBER
WHERE 1=1
and (D.DEPARTMENT_NUMBER = 300 or dr.department_number = 300)
and d.org_number = 2
AND D.DOCUMENT_TYPE IS NOT NULL
AND D.DOCUMENT_TYPE NOT IN (35,124,125,163)
--and acdsx.state_abbreviation is null
ORDER BY 1


SELECT D.DOCUMENT_NUMBER,D.ORG_NUMBER, D.DOCUMENT_NAME, D.DOCUMENT_PATH, D.DOCUMENT_FILE_NAME, D.DOCUMENT_TYPE, d.state_abbreviation, d.default_flag 
--, s.state_abbreviation 
--ACDSX.STATE_ABBREVIATION as APPROVED_STATE, acdsx.effective_date, acdsx.expiration_date, d.inactive_date 
, DRC.FIELD+DRC.OPERATOR+DRC.CRITERIAVALUE, D.DEPARTMENT_NUMBER AS DOC_DEPT, DR.DEPARTMENT_NUMBER as DOCRULE_DEPT, DR.RULE_SCRIPT, dr.description 
--, ACDSX.COMMENTS 
FROM DOCUMENTS D  
left join DocumentRuleXref DRX  
    on D.DOCUMENT_NUMBER = DRX.DOCUMENT_NUMBER 
LEFT JOIN DOCUMENTRULE DR  
          ON DRX.DOCUMENTRULEKEY = DR.DOCUMENTRULEKEY  
LEFT JOIN DOCUMENTRULECRITERIA DRC  
          ON DR.DOCUMENTRULEKEY = DRC.DOCUMENTRULEKEY  
LEFT JOIN RuleBasedDocType rbdt ON D.DOCUMENT_TYPE = rbdt.DocTypeId 
--join State s on s.state_abbreviation = s.state_abbreviation 
--LEFT JOIN ApprovedCoDocsStateXref ACDSX ON ACDSX.DOCUMENT_NUMBER = D.DOCUMENT_NUMBER 
WHERE 1=1 
--and (D.DEPARTMENT_NUMBER = 300 or dr.department_number = 300) 
and D.DEPARTMENT_NUMBER = 300  
and d.org_number = 2 
AND D.DOCUMENT_TYPE IS NOT NULL 
AND D.DOCUMENT_TYPE NOT IN (35,124,125,163) 
AND d.INACTIVE_DATE is NULL
--and acdsx.state_abbreviation is null 
--and s.capitalzipcode is not null 
ORDER BY 1


