

--
-- look for time in effective date (58 rows)
--
SELECT TOP 10000 s.SUB_POLICY_NUMBER, loc.INTERNAL_NAME, CAST(e.ENDORSEMENT_EFFECTIVE_DATE AS DATE)
FROM Endorsement e
JOIN Submission s ON e.SUB_RECORD_NUMBER = s.SUB_RECORD_NUMBER
JOIN dbo.PIPEndorsement pe ON pe.ENDORSEMENT_SKEY = e.ENDORSEMENT_SKEY
JOIN dbo.LOCATION loc ON e.LOCATION_SKEY = loc.LOCATION_SKEY
JOIN dbo.COMPANY c ON loc.COMPANY_SKEY = c.COMPANY_SKEY
WHERE 1=1
AND (DATEPART(MINUTE,ENDORSEMENT_EFFECTIVE_DATE) != 0
OR DATEPART(hour,ENDORSEMENT_EFFECTIVE_DATE) != 0)
ORDER BY ENDORSEMENT_CREATE_DATE DESC

--
-- look for time in expiration (0 results)
--
SELECT TOP 10000 s.SUB_POLICY_NUMBER, loc.INTERNAL_NAME, e.*
FROM Endorsement e
JOIN Submission s ON e.SUB_RECORD_NUMBER = s.SUB_RECORD_NUMBER
JOIN dbo.PIPEndorsement pe ON pe.ENDORSEMENT_SKEY = e.ENDORSEMENT_SKEY
JOIN dbo.LOCATION loc ON e.LOCATION_SKEY = loc.LOCATION_SKEY
JOIN dbo.COMPANY c ON loc.COMPANY_SKEY = c.COMPANY_SKEY
WHERE 1=1
AND (DATEPART(MINUTE,ENDORSEMENT_EXPIRATION_DATE) != 0
OR DATEPART(hour,ENDORSEMENT_EXPIRATION_DATE) != 0)
ORDER BY ENDORSEMENT_CREATE_DATE DESC