update EMPLOYEE set EMP_DEPARTMENT_NUMBER = 1900 where EMP_RECORD_NUMBER = 5300
update EMPLOYEE set EMP_DEPARTMENT_NUMBER = 100 where EMP_RECORD_NUMBER = 5300
update EMPLOYEE set EMP_DEPARTMENT_NUMBER = 1800 where EMP_RECORD_NUMBER = 5300
update EMPLOYEE set EMP_DEPARTMENT_NUMBER = 300 where EMP_RECORD_NUMBER = 5300
update EMPLOYEE set EMP_DEPARTMENT_NUMBER = 200 where EMP_RECORD_NUMBER = 5300
update EMPLOYEE set EMP_DEPARTMENT_NUMBER = 10006 where EMP_RECORD_NUMBER = 5300
update EMPLOYEE set EMP_DEPARTMENT_NUMBER = 10005 where EMP_RECORD_NUMBER = 5300
update EMPLOYEE set EMP_DEPARTMENT_NUMBER = 10006, EMP_BRANCH_NUMBER=100 where EMP_RECORD_NUMBER = 5300
update EMPLOYEE set EMP_DEPARTMENT_NUMBER = 200, EMP_BRANCH_NUMBER=200 where EMP_RECORD_NUMBER = 5300
update EMPLOYEE set EMP_DEPARTMENT_NUMBER = 600 where EMP_RECORD_NUMBER = 5300